// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svzztlfpvzlsjwsbrgqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2enp0bGZwdnpsc2p3c2JyZ3FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMzUwMTksImV4cCI6MjA3MjkxMTAxOX0.qLv1rblibxKaTtK2ahZH6uzqfgJCOR9IAUlyuJOFkjo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});